clone_folder: c:\project\opencpn
shallow_clone: true
image:
- Visual Studio 2017

platform: 
# - x64
- Win32

configuration: Release
test: OFF

install:
  # VS2015 and earlier version - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  
  # sent environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets-3.1.1
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - cmd: SET PATH=%PATH%;%WXWIN%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;

  # install dependencies:
  - choco install poedit

  # - choco install nsi -x86
  - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/nsis-3.03-setup.exe
  - cmd: nsis-3.03-setup.exe /S

  # Download and unzip wxwidgets
  - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/wxWidgets-3.1.1.7z
  - cmd: 7z x wxWidgets-3.1.1.7z -o%WXWIN% > null

  # some debugging information
  - set
  # - cmake --help

  # build wxWidgets - Disabled as we provide prebuilt WX to save time
  #- cmd: cd %WXWIN%\build\msw\
  #- cmd: nmake -f makefile.vc BUILD=release SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_
  #- cmd: nmake -f makefile.vc BUILD=debug SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_

before_build:
  - cd c:\project\opencpn
  - mkdir build
  - cd build
  - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/OpenCPN_buildwin-4.99.7z
  - cmd: 7z x -y OpenCPN_buildwin-4.99.7z -oc:\project\opencpn\buildwin
  - cmake -T v141_xp ..

build_script:
  # - cmake --build . --config debug
  - cmake --build . --target opencpn --config release
  - cmake --build . --target package --config release
  # --target package doesn't work because of nsis not correctly installed

artifacts:
  - path: 'build\*.exe'
    name: installer

  - path: 'build\Release\opencpn.lib'
    name: lib

deploy:
  description: 'release created by AppVeyor CI'
  provider: GitHub
  auth_token: '%GitHub_auth_token%'
  artifact: installer,lib
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true # deploy on tag push only
    configuration: Release  # Debug contains non-redist MS DLLs
