clone_folder: c:\project\opencpn
shallow_clone: true
image:
- Visual Studio 2015

platform: 
# - x64
- Win32

configuration: Release
test: OFF

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'

  # sent environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets-3.0.2
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - cmd: SET PATH=%PATH%;%WXWIN%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;

  # install dependencies:
  - choco install poedit -x86

  - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/nsis-3.03-setup.exe
  - cmd: nsis-3.03-setup.exe /S

  # Download and unzip wxwidgets
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/wxwindows/3.0.2/wxWidgets-3.0.2.zip
  - cmd: 7z x wxwidgets-3.0.2.zip -o%WXWIN% > null

  # some debugging information
  - set
  # - cmake --help

  # build wxWidgets
  - cmd: cd %WXWIN%\build\msw\
  - cmd: nmake -f makefile.vc BUILD=release SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_
  - cmd: nmake -f makefile.vc BUILD=debug SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_

before_build:
  - cd c:\project\opencpn
  - mkdir build
  - cd build
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/opencpnplugins/opencpn_packaging_data/OpenCPN_buildwin.7z
  - cmd: 7z x -y OpenCPN_buildwin.7z -oc:\project\opencpn
  - cmake -T v120_xp ..

build_script:
  # - cmake --build . --config debug
  - cmake --build . --target opencpn --config release
  - cmake --build . --target package --config release
  # --target package doesn't work because of nsis not correctly installed

artifacts:
  - path: 'build\*.exe'
    name: installer

  - path: 'build\Release\opencpn.lib'
    name: lib

deploy:
  description: 'release created by AppVeyor CI'
  provider: GitHub
  auth_token: '%GitHub_auth_token%'
  artifact: installer,lib
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true # deploy on tag push only
    configuration: Release  # Debug contains non-redist MS DLLs
